### ISSUE TITLE
Can't deploy a dockerized SUT using commands 

### ISSUE THREAD

**Issue by fermenreq** [elastest/elastest-torm#20]
#### Characteristics
- **Issue Type**: bug
- **Reproducibility**: always,
- **Severity**: [major, crash]
- **Tool/Service/Component**: [Elastest Torm, elastest/eim-sut:latest]
- **Execution Environment**: [Linux VM]
- **Reporter**: Fernando Mendez Requena - fernando.mendez@atos.net

#### Description
There is no possibility to launch a dockerized SUT by adding flags commands into the RUN stattment as [Readme](https://elastest.io/docs/testing/sut/) said in chapter "_**SuT deployed by ElasTest: With Commands Container**_". This behaivour cause a crash into EIM Api Rest tests reporting as a connection refused, also cause a build failed to e2e tests 

#### Steps to reproduce

![image](https://user-images.githubusercontent.com/25005913/63498392-16681780-c4c6-11e9-91aa-7919f63474e8.png)

##### Command Line / Options
`docker pull elastest/eim-sut:latest; docker run --rm --cap-add=NET_ADMIN --name $ET_SUT_CONTAINER_NAME elastest/eim-sut:latest;`

#### Relationships
 [Elastest Instrumentation Manager](https://github.com/elastest/elastest-instrumentation-manager)

**Comment by EduJGURJC** [comment]
Hi,

The problem occurs when there is **no port to wait for the sut**. The TJob container starts before the Sut container and therefore the value of the `ET_SUT_HOST` variable is the IP of the _sut_aux_. I've made a change so that, even if you don't specify a port, you wait a couple of minutes for the sut container and set its IP as the value of the variable. Try it now and tell us if it works.

Thank you

**Comment by fermenreq** [comment]
@EduJGURJC this issue can be closed.  Problem solved! Thanks
![image](https://user-images.githubusercontent.com/25005913/63505286-9052cd80-c4d3-11e9-92c1-cb9031b64565.png)

**Comment by EduJGURJC** [comment]
Nice!

> Solved with commit 91f3518e6884aced6e9111df3a911ab331485907
